spring:
    application:
        name: projektio-backend

    datasource:
        url: jdbc:h2:file:./data/KFD;
        username: user
        password: pass
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
        show-sql: true

server:
    port: 8083
    servlet:
        context-path: /api

jwt:
    key: "top_secret_key_and_it_has_to_be_longer_than_256_bits" # Has to be from env var
    access-token-expiration-date: 3600000
    refresh-token-expiration-date: 86400000